Q1

In [13]:
#(a)
import numpy as np 
arr=np.array([1,2,3,6,4,5])
rev=np.flip(arr)
print("reverse is",rev)

reverse is [5 4 6 3 2 1]


In [14]:
#b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatt=array1.flatten()
print(flatt)
flat3=array1.reshape(-1)
print("using reshape(-1):",flat3)


[1 2 3 2 4 5 1 2 3]
using reshape(-1): [1 2 3 2 4 5 1 2 3]


In [15]:
#(c)
arr1=np.array([[1, 2],[3, 4]])
arr2=np.array([[1, 2],[3, 4]])
print(arr1==arr2)


[[ True  True]
 [ True  True]]


In [16]:
#e
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
s=np.sum(gfg)
r=np.sum(gfg,axis=1)
c=np.sum(gfg,axis=0)
print(s)
print(r)
print(c)




45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [17]:
#f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag=np.trace(n_array)

eigen_values, eigen_vectors = np.linalg.eig(n_array)
inverse=np.linalg.inv(n_array)
deter=np.linalg.det(n_array)
print(diag)
print(deter)
print(inverse)

176
137180.0000000001
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [18]:
#g
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
p_f=np.array(p).flatten()
q_f=np.array(q).flatten()
mul=np.dot(p,q)
print(mul)
cov=np.cov(p_f,q_f)
print(cov)
p1 = [[1, 2], [2, 3], [4, 5]]
q1 = [[4, 5, 1], [6, 7, 2]]
p_f1=np.array(p1).flatten()
q_f1=np.array(q1).flatten()
multi=np.dot(p1,q1)
print(multi)
cov1=np.cov(p_f1,q_f1)
print(cov1)



[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [19]:
#h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inn=np.inner(x,y)
out=np.outer(x.flatten(),y.flatten())
print("inner",inn)
print("outer",out)


inner [[17 52]
 [13 62]]
outer [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


Q2

In [20]:
#a
array = np.array([[1, -2, 3],[-4, 5, -6]])
ab=np.absolute(array)
print(ab)
flat=array.flatten()
print(flat)
p_25=np.percentile(flat,25)
p_50=np.percentile(flat,50)
p_75=np.percentile(flat,75)
print(p_25)
print(p_50)
print(p_75)
print("/ncol")
cp=np.percentile(array,[25,50,75],axis=0)
print(cp)
print("/n row")
rp=np.percentile(array,[25,50,75],axis=1)
print(rp)

[[1 2 3]
 [4 5 6]]
[ 1 -2  3 -4  5 -6]
-3.5
-0.5
2.5
/ncol
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
/n row
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [21]:

print("mean",np.mean(flat))
print("median",np.median(flat))
print("sd",np.std(flat))
print("/n column")
print("mean",np.mean(array,axis=0))
print("median",np.median(array,axis=0))
print("sd",np.std(array,axis=0))
print("/n row")
print("mean",np.mean(array,axis=1))
print("median",np.median(array,axis=1))
print("sd",np.std(array,axis=1))



mean -0.5
median -0.5
sd 3.8622100754188224
/n column
mean [-1.5  1.5 -1.5]
median [-1.5  1.5 -1.5]
sd [2.5 3.5 4.5]
/n row
mean [ 0.66666667 -1.66666667]
median [ 1. -4.]
sd [2.05480467 4.78423336]


In [22]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("floor",np.floor(a))
print("ceil",np.ceil(a))
print("trunc",np.trunc(a))
print("round",np.round(a))

floor [-2. -2. -1.  0.  1.  1.  3.]
ceil [-1. -1. -0.  1.  2.  2.  3.]
trunc [-1. -1. -0.  0.  1.  1.  3.]
round [-2. -2. -0.  0.  2.  2.  3.]


Q3

In [23]:
#a
array = np.array([10, 52, 62, 16, 16, 54, 453])
st=np.sort(array)
print("sorted",np.sort(array))
print("indices",np.argsort(array))
print("smalllest",st[:4])
print("largest",st[-5:])

sorted [ 10  16  16  52  54  62 453]
indices [0 3 4 1 5 2 6]
smalllest [10 16 16 52]
largest [ 16  52  54  62 453]


In [24]:
#b
array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
flr=np.floor(array2)
print("intt",array2==flr)
print("float",array2!=flr)

intt [ True False False  True  True  True]
float [False  True  True False False False]
